# Generated by Django 3.1.4 on 2021-05-20 19:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categ_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_categ_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Sub-Categoria')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaMPRO.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Tipo de Producto')),
                ('sub_categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaMPRO.subcategoria', verbose_name='SubCategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prod', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nombre de Producto')),
                ('descripcion', models.TextField(blank=True, max_length=1500, null=True)),
                ('precio', models.FloatField(default=0.0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/producto')),
                ('tipo_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendaMPRO.tipoproducto')),
            ],
        ),
    ]
