# Generated by Django 3.2.3 on 2021-05-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMPRO', '0004_rename_product_productopedido_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='retiroTienda',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
