# Generated by Django 3.2.3 on 2021-05-27 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMPRO', '0007_alter_ordendecompra_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direcciondeenvio',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
