# Generated by Django 3.2.3 on 2021-05-27 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMPRO', '0008_alter_direcciondeenvio_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
