# Generated by Django 3.1.4 on 2021-05-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMPRO', '0011_auto_20210527_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estrategiadeventa',
            name='user',
        ),
    ]
