# Generated by Django 3.1.4 on 2021-06-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMPRO', '0013_auto_20210624_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_admin',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_bodega',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_contador',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_vend',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
