# Generated by Django 3.2.3 on 2021-06-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMPRO', '0013_auto_20210624_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_bodega',
            field=models.BooleanField(default=False, verbose_name='Bodeguero'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_contador',
            field=models.BooleanField(default=False, verbose_name='Contador'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_vend',
            field=models.BooleanField(default=False, verbose_name='Vendedor'),
        ),
    ]
