# Generated by Django 3.2.3 on 2021-06-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMPRO', '0014_auto_20210624_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='pagado',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='transferencia',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_bodega',
            field=models.BooleanField(default=False, null=True, verbose_name='Bodeguero'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_contador',
            field=models.BooleanField(default=False, null=True, verbose_name='Contador'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_vend',
            field=models.BooleanField(default=False, null=True, verbose_name='Vendedor'),
        ),
    ]
