# Generated by Django 3.1.4 on 2021-06-26 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMPRO', '0015_auto_20210625_1344'),
        ('TiendaMPRO', '0014_auto_20210624_1627'),
    ]

    operations = [
    ]
