# Generated by Django 3.2.3 on 2021-06-26 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMPRO', '0016_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='order',
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='ciudad',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='SucursalDeEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TiendaMPRO.ordendecompra')),
            ],
        ),
    ]
