# Generated by Django 3.1.4 on 2021-06-28 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMPRO', '0017_auto_20210626_1843'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pagos',
            new_name='Pago',
        ),
    ]
