# Generated by Django 3.2.3 on 2021-06-27 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMPRO', '0018_auto_20210627_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direcciondeenvio',
            name='fecha_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
