# Generated by Django 3.2.3 on 2021-06-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMPRO', '0019_alter_direcciondeenvio_fecha_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='aceptada',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
