# Generated by Django 3.2.3 on 2021-06-28 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMPRO', '0021_auto_20210628_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordendecompra',
            old_name='despachada',
            new_name='orden_bodega',
        ),
    ]
