# Generated by Django 3.2.3 on 2021-06-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMPRO', '0022_rename_despachada_ordendecompra_orden_bodega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendeentrega',
            name='ciudad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordendeentrega',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordendeentrega',
            name='fecha_de_entrega',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ordendeentrega',
            name='pais',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
