# Generated by Django 3.2.3 on 2021-06-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMPRO', '0023_auto_20210628_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendeentrega',
            name='aceptada',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
