# Generated by Django 3.2.3 on 2021-06-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMPRO', '0024_ordendeentrega_aceptada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendeentrega',
            name='aceptada',
        ),
        migrations.AddField(
            model_name='ordendeentrega',
            name='estado',
            field=models.CharField(blank=True, default='En Espera', max_length=200, null=True),
        ),
    ]
