# Generated by Django 3.2.3 on 2021-06-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMPRO', '0025_auto_20210628_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendeentrega',
            name='estado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
