# Generated by Django 3.2.3 on 2021-06-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMPRO', '0027_auto_20210628_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendecompra',
            name='estado',
            field=models.CharField(blank=True, default='En Bodega', max_length=200, null=True),
        ),
    ]
