# Generated by Django 3.2.3 on 2021-06-29 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMPRO', '0018_auto_20210628_0013'),
        ('TiendaMPRO', '0028_alter_ordendecompra_estado'),
    ]

    operations = [
    ]
