# Generated by Django 3.2.3 on 2021-06-30 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaMPRO', '0029_merge_20210629_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendecompra',
            name='date_orderd',
        ),
    ]
